framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
            #slack: '%ENV(SLACK_DSN)'
        texter_transports:
            freemobile: '%env(FREE_MOBILE_DSN)%'
            free: '%env(FREE_MOBILE_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
